description: >
  Default executor
docker:
  - image: cimg/base:<<parameters.tag>>
parameters:
  tag:
    default: "2021.04"
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
